### ISSUE TITLE
Cannot Run the executable of example project  on Nexus-5

### ISSUE THREAD

**Issue by pg2527** [IAIK/armageddon#1]
An error  pops up the moment I run the executable (built for armv7) on a non rooted Nexus 5.
I am running the executable from /data/local/tmp folder.  I have built the example project separately using NDK toolchain
![test](https://cloud.githubusercontent.com/assets/17165273/20567772/4cd70372-b19a-11e6-9c38-d7ff689b7471.png)

**Comment by mlq** [comment]
I assume that you did not change anything in the build configuration. By default the `TIME_SOURCE` flag is set to `register` which means that libflush will try to access the performance counters directly. This is not allowed by default. If you have access to the perf interface you can set `TIME_SOURCE` to `perf`. Otherwise I suggest to use `monotonic_clock` or `thread_counter` as an alternative timing source.

You can change this variable in `config.mk` or pass it directly to make (e.g.: make TIME_SOURCE=perf).

**Comment by pg2527** [comment]
Yeah. It worked. Thanks a lot !!
